name: Deploy to Github Pages
on:
  push:
    branches:
      - delivery
jobs:
  gh-pages-deploy:
    name: Deploying to Github Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '22.13.0'
      - name: Install packages
        run: yarn install
      - name: Set Creds
        run: git config user.name "Metroslim" && git config user.email "arnmasson@gmail.com"
      - name: Deploy
        run: yarn deploy
